### PR TITLE
feature: skip FlushMock when it return a nil.

### PR DESCRIPTION
**Pull request by lentil1016**
# What this pull request do

Let `Flush` continuing its following job when the dummy function `FlushMock` user defined returned with a nil, instead of return that nil.

# Where do I need it

Consider the following function. If I hope to let my tests cover the second fail point in it, I'll need to let first `Flush` call return without an error. And this PR will allow user to achieve that with an appropriate dummy closure function.
```
func some2PhaseHandler(conn redis.Conn) string {
	conn.Send("PING")
	err := conn.Flush()
	if err != nil {
		// fail point 1
		return nil
	}
	result, _ := conn.Receive()

	if result == "PING" {
		conn.Send("PING")
		err = conn.Flush()
		if err != nil {
			// fail point 2
			return nil
		}
		finResult, _ := conn.Receive()
	}
	return finResult
}
```

### CODE REVIEW

**Comment by rafaeljusto** [comment]
Hey @lentil1016 , thanks for the patch. Yeah, you're right, as those properties are private there's no way to clear the queue in the `FlushMock` call. I'm just worried about backwards compatibility, as this will be a behaviour change of the `FlushMock` 🤔. Changing the call to `FlushMock() (clearQueue bool, err error)` could be even more aggressive change but would guarantee both behaviours. Let me think a little about this one.

**Comment by lentil1016** [comment]
@rafaeljusto Hey, Thanks for your feedback. You are right, this is aggressive. I'm not sure, maybe add a new dummy function signature is a possible approach. Though it seems pretty hard to come up with a clear name.

```go
// Flush can be mocked using the Conn struct attributes
func (c *Conn) Flush() error {
	if c.FlushMock != nil {
		return c.FlushMock()
	}
	if c.FlushMockWillContinue != nil {
		if err := c.FlushMockWillContinue(); err != nil {
			return err
		}
	}

	if len(c.queue) > 0 {
		for _, cmd := range c.queue {
....
```

**Comment by rafaeljusto** [comment]
> Though it seems pretty hard to come up with a clear name.

This is the most difficult part of programming. 😆 

Yeah, let's go with the `FlushSkippableMock`. Could you patch your PR please?

**Comment by lentil1016** [comment]
Good to go. ; )

**Comment by rafaeljusto** [comment]
Thanks for the contribution @lentil1016 !

**Pull request merged**
